### ISSUE TITLE
Document Differences between Slidl and PathML

### ISSUE THREAD

**Issue by jpfeil** [markowetzlab/slidl#2]
PathML and Slidl appear to have similar functions, but I haven't seen documentation explaining what the difference are. Should I use one over the other? It looks like slidl is the most recently updated but pathml has been around longer and appears first when searching for whole slide image preprocessing software.

**Comment by agberman** [comment]
Hi Jacob,

SliDL is the most updated version with the same functionalities as PathML with some additional ones. PathML is a legacy version.
